name: nodejs to azure wap
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: nodejs-wap    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  ROOT_PATH: './actions/nodejs/myExpressApp'

jobs:
  build:
    strategy:
      matrix:
        node-version: [16.x] #12.x, 14.x,
        os: [ubuntu-18.04] #macos-latest, windows-latest, 

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version:  ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '${{ env.ROOT_PATH }}/package-lock.json'


    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
      working-directory: ${{ env.ROOT_PATH }}

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: node-app
        path: .


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: node-app
        path: ${{ env.DOTNET_ROOT }}


    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp 
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_NODEJS_APP_PUBLISH_PROFILE }}
        package: ${{ env.ROOT_PATH }}